
export const SET_SINGER = 'SET_SINGER';

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE';

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN';

export const SET_PLAY_LIST = 'SET_PLAY_LIST';

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST';

export const SET_MODE = 'SET_MODE';

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX';

export const SET_SONG_LIST = 'SET_SONG_LIST';

export const SET_RANK_LIST = 'SET_RANK_LIST';

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY';

export const SET_PLAY_HISTORY = 'SET_PLAY_HISTORY';

export const SET_FAVORITE_LIST = 'SET_FAVORITE_LIST';
